### ISSUE TITLE
Client::uploadSlicedFile chunks

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#103]
Vokurkovi se stalo, že mu paralelní upload slices neproběhl (nebo trval extrémně dlouho). Důvody vidím dva

a) too many open files 
b) errory v transferu (který vyvolaj restart celýho procesu) 

ad a) to se kousne na definovaným počtu otevřených souborů
ad b) se zhoršuje s rostoucím počtem sliců

Benchmarkuju teď že by se uploady dávkovaly a zatím to nevypadá, že by rozdělení uploadu po 50 souborech nějak výrazně zpomalovalo upload. Bug A to vyřeší úplně, dopad bugu B to minimalizuje.

Přemýšlím, že by se počet souborů v dávce dal nastavit na straně klienta. Default bych nechal asi na 50 (nemám lepší číslo) a volitelně by to bylo možný přetíži buď při volání metody `Client::uploadSlicedFile` nebo v konfigurační classe `FileUploadOptions`. Co z toho by bylo lepší?

**Comment by Halama** [comment]
A ty důvody odhaduješ nebo to někde zalogovalo nějakou chybu?

Jinak bych tam klidně dal ten default na 50 a dal to jako další parametr té `uploadSlicedFile` metody protože v tom `FileUploadOptions` jsou jenom parametry které jdou do SAPI a tohle je parametr naopak jenom klienta, tak bych to asi radši držel bokem. Takže třeba `transferOptions` nebo něco takového?

**Comment by ondrejhlavacek** [comment]
Důvody odhaduju, zalogovanýho není nic, i když bych čekal, že bude :-(
Pokud tohle nezabere (to je celkem jednoduchej fix), tak to budu muset pořádně odebugovat.

**Comment by Halama** [comment]
ok tak bych to udelal takhle

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/storage-api-php-client/pull/104

**Comment by ondrejhlavacek** [comment]
fixed by https://github.com/keboola/storage-api-php-client/pull/104
