### ISSUE TITLE
Allow also psr/log ^2||^3

### ISSUE THREAD

**Issue by VNovotna** [keboola/storage-api-php-client#1082]
Hello, 

Is there any chance you could also allow `psr/log` versions 2 and 3, please? 

It prevents us from using the latest versions of spiral/roadrunner components. 

Thank you very much!

**Comment by tomasfejfar** [comment]
Could you please send a PR that is working for you for us to run test on and consider. There is a chance that you'd be blocked by other packages as well.

**Comment by jirkasemmler** [comment]
fixed here https://github.com/keboola/storage-api-php-client/pull/1231
