### ISSUE TITLE
Keboola Storage API PHP Client/6.1.0 Keboola Storage API CLI/@package_version@

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#120]
Z nějakýho důvodu se v logu začalo objevovat v user agentu tohle

```
Keboola Storage API PHP Client/6.1.0 Keboola Storage API CLI/@package_version@
```

Je to správně? Nepamatuju si, že by tam dřív to `@package_version@` bylo...

**Comment by pivnicek** [comment]
looks like the CLI has had @package_version@ there since the beginning https://github.com/keboola/storage-api-cli/commit/ebe9b86158868c9b68a5cc998532bf10172410ae

**Comment by Halama** [comment]
no, it is generated on build.

**Comment by pivnicek** [comment]
aha

**Comment by Halama** [comment]
I am closing this, not related to client
