### ISSUE TITLE
Parsing API responses in Client changes empty objects into arrays

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#126]
Happens here - https://github.com/keboola/storage-api-php-client/blob/c6d64279e1e83a8848c319218046602cdad4f917/src/Keboola/StorageApi/Client.php#L1866

Should use either `json_decode($jsonString)` (without `assoc` param) or return a new class, eg `Result`, as in AWS (preferable).

**Comment by ondrejhlavacek** [comment]
Then revert https://github.com/keboola/kbc-ui/commit/fdfc7c49ffa7582e095b77340e427daca4bb5e25

**Comment by Halama** [comment]
It caused problems again https://keboola.slack.com/archives/C02CGRFH8/p1518856186000086

**Comment by ErikZigo** [comment]
Moved to Jira https://keboola.atlassian.net/browse/KBC-1811
