### ISSUE TITLE
4 GB file limit

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#131]
Use `\Aws\S3\MultipartUploader` where applicable (file uploads) to 
- avoid 4 GB file limit
- speed up the upload

Derived from `Client::uploadSlicedFile`, can share some of the code.

**Comment by pivnicek** [comment]
@ondrejhlavacek just for reference (not sure how related they are) there are 2 connection issues related to max file size upload afaik
https://github.com/keboola/connection/issues/205
https://github.com/keboola/connection/issues/752

**Comment by ondrejhlavacek** [comment]
@pivnicek thanks for the note. https://github.com/keboola/connection/issues/752 will be fixed by this update, not sure about https://github.com/keboola/connection/issues/205 for now.

**Comment by ondrejhlavacek** [comment]
Narazil jsem na jeden trochu zádrhel v testech. V SDK doporučujou použít MultipartUpload pro soubory >100 MB, ale nic takovýho v testu mít nechci. Ale nejsem si jistej, jestli zapnutí MultipartUploadu plošně pro všechny uploady nebude mít nějakej negativní dopad.

**Comment by Halama** [comment]
myslím že by ho to mělo použít jen pro ty nad 100MB.

**Comment by ondrejhlavacek** [comment]
Nj, ale to budu muset v testech uložit nebo generovat 100MB soubor, aby se otestovalo, že to šlape. Nebo přes `FileUploadOption` určovat hranici, od které se použije ten multipart.

**Comment by ondrejhlavacek** [comment]
Zkusím to přes `setMultipartTreshold` v `FileUploadOption` a testovat to na nějakém menším souboru.

**Comment by Halama** [comment]
Releasnuto jako 6.4.0 https://github.com/keboola/storage-api-php-client/blob/master/CHANGELOG.md#640-2017-05-27
