### ISSUE TITLE
Misleading assert fail message

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#138]
`...version should be 4` but the assert expects `5`.

https://github.com/keboola/storage-api-php-client/blob/8e77401f866d388c43e64fcd92b6df6a06b278fe/tests/Common/ComponentsTest.php#L862

**Comment by Halama** [comment]
tomu nerozumím, když  by to tak bylo tak ten test nebude procházet

**Comment by ondrejhlavacek** [comment]
V popisku je ale něco jinýho než v assert.
