### ISSUE TITLE
Add some examples to apiary about loading data to workspace

### ISSUE THREAD

**Issue by ujovlado** [keboola/storage-api-php-client#144]
Alebo mozno do https://github.com/keboola/developers-docs?

Mal som na to ticket a napr. pre `datatypes` to moc jasne nie je:

![screenshot_2017-08-15_18-44-28](https://user-images.githubusercontent.com/419849/29325938-db4b5c5a-81e9-11e7-9282-816616424270.png)

**Comment by odinuv** [comment]
radsi do docs

**Comment by ErikZigo** [comment]
To si vezmu na starosti asi ja, az dodelam ty inkrementalni loady.

To je moc dobry napad. Jsem si u toho "vylamal" zuby a zjistoval to tak, ze jsem si musel nakonfigurovat nejakou transformaci. A pak z detailu jobu zkoumal jaky parametry se tam maj poslat.

**Comment by Halama** [comment]
sis to mohl precist v testech

**Comment by Halama** [comment]
a dival jsem se ze v te dokumentaci to je ale apiary to nerenderuje uz hloubeji asi

**Comment by odinuv** [comment]
renderuje, ale nebyl tam datovej typ 5e7155302695fcde6fe82216db08423adc1407d7

**Comment by ujovlado** [comment]
Aha, zaujimave ... myslis, ze to rovnako pojde aj pre ten object? Lebo tam sa to da zadat dvoma sposobmi.

**Comment by odinuv** [comment]
to takhle z hlavy nevim jestli to nejaky zakouti msonu podporuje, osobne bych tam napsal neco jako see below a link do dokumentace na priklad, kterej bude beztak uzitecnejsi

**Comment by odinuv** [comment]
no da se tam napsat taky `datatypes{} (optional, array) a zkopirovat to od `+ Items` ono je otazka jestli je to object nebo array, kdyz je to stejne form-encoded ve kterym nic takovyho neni

**Comment by martinjunger** [comment]
vyresime pomoci JSON requestu
