### ISSUE TITLE
AWS client instantiation - proxy option and other options

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-php-client#146]
AWS S3 client is created internally a we don't allow users to specify other options like `proxy` settings.

https://keboola.zendesk.com/agent/tickets/7159

**Comment by Halama** [comment]
proxy by rádi používali i pro samotné KBC v klientovi https://keboola.zendesk.com/agent/tickets/7221

**Comment by ErikZigo** [comment]
To nevypada vubec slozite.

Akorat pridat u klienta do konfigurace `proxy` a metodu `getProxy`

A tam kde se pouziva S3 Client, tak nastavit proxy podle konfigurace SAPI klienta
http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html?highlight=proxy#proxy

**Comment by janmichek** [comment]
@ErikZigo muzu to napsat jako odpoved na tenhle ticket? https://keboola.zendesk.com/agent/tickets/7221
