### ISSUE TITLE
Job backoff delays

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#171]
U malejch jobů je hodně velkej overhead v backoffu. Job, co je za 8 vteřin hotovej, trvá ještě 7 vteřin, než doputuje do docker runneru (1+2+4+8). Co to nějak optimailizovat? Třeba prvních 30 vteřin po vteřině, pak minutu po dvou, a pak to nějak plynule zvedat na těch 20?

**Comment by Halama** [comment]
to uz je vyreseno.

**Comment by ondrejhlavacek** [comment]
jak?

**Comment by Halama** [comment]
https://github.com/keboola/storage-api-php-client/blob/master/CHANGELOG.md#721-2017-11-13

**Comment by Halama** [comment]
staci nasadit na docker runner a transformace

**Comment by ondrejhlavacek** [comment]
takže bys hodil `maxJobPollWaitPeriodSeconds` třeba na 1s?

**Comment by Halama** [comment]
zacal bych treba s 10 a chvili sledoval jak to zmeni zatez, a pak sel niz.

**Comment by ondrejhlavacek** [comment]
současně s tím bude potřeba zvednout `backoffMaxTries`

**Comment by Halama** [comment]
Proč? to s tím vůbec nesouvisí.

**Comment by ondrejhlavacek** [comment]
Aha, `maxJobPollWaitPeriodSeconds` teda jede donekonečna?

**Comment by Halama** [comment]
jj

**Comment by ondrejhlavacek** [comment]
oukej, zkusím to začít protlačovat, ale imho to dojde do stavu, kdy nějaký rozumný nastavení bude penalizovat malý joby a nebo velký joby budou floodovat spoustou requestů.

**Comment by Halama** [comment]
tak se to muze poladit tak jak si psal, ale ani u malejech by to nemelo nejak brutalne prasit.

**Comment by pivnicek** [comment]
@ondrejhlavacek I remember doing this in syrup client here: https://github.com/keboola/syrup-php-client/blob/master/src/Keboola/Syrup/Client.php#L93

Where you can override the delay method

**Comment by ondrejhlavacek** [comment]
Trocha analýzy (počty jobů vzhledem k public github repo maskuju)

![image](https://user-images.githubusercontent.com/497675/35281218-a52ff940-0052-11e8-9c5a-33075ab75d61.png)

Konkrétní údaje tady. Hranice bucketů jsem volil přesně podle exponenciálního delaye (`POW(2, n)`).

Procenta tam nejsou, to už jsem v SQL nedokázal tak snadno vyrobit, přes WINDOW fce mi to nějak nešlo.

- segment 7-15 vteřin (přes 60 % všech jobů) průměrně zbytečně čeká přes 5 vteřin
- segment 15-31 vteřin (~15 % všech jobů) průměrně zbytečně čeká přes 9 vteřin
- jobů delších než 31 vteřin je ~5 %
- jobů kratších než 7 vteřin je ~10 %

Pokud s tím něco chcem udělat, tak nám nepomůže snížit globální limit na 10 ani 5 vteřin, musíme prvních 30 vteřin intenzivně bombit API a dostat co nejrychleji odpověď, pak už je to jedno.

https://connection.keboola.com/admin/projects/258/jobs/349095007/tables/out.c-sapi-delays.histogram
https://connection.keboola.com/admin/projects/258/transformations/bucket/349080091/transformation/349080115

**Comment by ondrejhlavacek** [comment]
https://keboola.slack.com/archives/C02CGRFH8/p1516721539000430

Začít s featurou projektu a udělat krokovou funkci (https://keboola.slack.com/archives/C02CGRFH8/p1516722959000827)

**Comment by Halama** [comment]
s tou featurou byl ale imho melo pracovat to bude toho klienta vytvaret a podle toho mu dat jednu nebo druhou delay policy.

**Comment by ondrejhlavacek** [comment]
co by s ní mělo pracovat? sapi client nebo appka, která pouští sapi clienta?

**Comment by Halama** [comment]
appka ktere vytvari klienta

**Comment by ondrejhlavacek** [comment]
jj, určitě!

**Comment by Halama** [comment]
Done in #180
