### ISSUE TITLE
Error executing "PutObject": InvalidToken

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#173]
```
Error executing "PutObject" on "https://***.csv.gz"; 
AWS HTTP error: 
Client error: 
`PUT https://***.csv.gz` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidToken</Code><Message>The provided token is malformed or other (truncated...)
```

Stalo se nahodile, ale klient by mohl udělat na celej upload včetně generování credentials retry.

https://connection.keboola.com/admin/utils/logs?file=2018/01/31/03/2018-01-31-03-03-00-5a7123d4c0ff1-exception
https://connection.keboola.com/admin/utils/logs?file=2018/01/31/03/2018-01-31-03-03-00-5a7123d4d71d8-log

**Comment by ErikZigo** [comment]
S tím jsem se v poslední delší době nesetkal. Ani na to není podobné issue v Jira. Tak zavírám.
