### ISSUE TITLE
Batch Workspace Unload

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#237]
Určeno pro zrychlení unload dat z workspace transformace do storage. Load do workspace se zrychlí klonovacím input mappingem. 

Ořízl bych paralelizovanou logiku pouze na unload dat. Založení bucketu, metadata a smazání rows se bude řešit serializovaně jako teď. 

`Client::writeTableAsyncDirect` a `Client::createTableAsyncDirect` by mohly mít nepovinný argument `$handleAsyncTask`, který zpropaguje id jobu a nebude čekat  na jeho dokončení.

Podobně jako v https://github.com/keboola/storage-api-php-client/issues/236 se budou pollovat joby a vyhazovat chyby, tentokrát to ale budou handlovat transformace, takže `Client::handleAsyncTaskResponse` bude public. 

V transformacích se bude muset output mapping trochu přeházet. 

### Sync metadat

Trochu mám problém rozhodnout, jak s metadatama. Tyhle paralelní joby povedou k tomu, že metadata nebudou správně nastavený. Jde o tyhle klíče metadat

```
KBC.createdBy.component.id
KBC.createdBy.configuration.id
KBC.createdBy.configurationRow.id
KBC.lastUpdatedBy.component.id
KBC.lastUpdatedBy.configuration.id
KBC.lastUpdatedBy.configurationRow.id
```

Podobný problém se bude muset vyřešit i v https://github.com/keboola/output-mapping. 

#### Optimistický přístup

Pokud bychom řekli, že můžeme updatovat metadata před unloadem tabulky, tak se přes async jobama založí chybějící tabulky, nastaví metadata a pak se hromadně nasypou joby. V případě chyby metadata (a prázdný tabulky) zůstanou i když se akce nestala

#### Pesimistický přístup

Metadata se pošlou až hromadně na konci, když se všechny tabulky importují správně. Při failu jakéhokoliv importu budou všechny metadata chybět.

#### Sync přístup

Metadata budou součástí payloadu jobu, který do tabulky importuje nebo tabulku zakládá. Storage se postará o to, aby se v případě úspěchu metadata zapsaly.

---

ref https://github.com/keboola/internal/issues/48
ref https://github.com/keboola/storage-api-php-client/issues/236
ref https://github.com/keboola/storage-api-php-client/issues/233

**Comment by pivnicek** [comment]
imho ten **Sync přístup** dava smysl

**Comment by ondrejhlavacek** [comment]
v output mappingu se metadata zapisují dopředu, tak to transformace udělají stejně.
