### ISSUE TITLE
Sliced file upload - merge small slices

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-php-client#244]
Merge small slices to slice sizes [recommended by Snowflake](https://docs.snowflake.net/manuals/user-guide/data-load-considerations-prepare.html#general-file-sizing-recommendations) before upload.

**Comment by ondrejhlavacek** [comment]
Stálo by za to udělat benchmark, jestli to bude mít nějakej zásadní vliv. Na extrémy typu tisíc souborů po jednom řádku bych se vybodl. Do toho bude hodně vstupovat komprese, kterou nejsme schopný predikovat (teď se mi 5GB soubor s náhodnejma alfanumerickejma znakama zkomprimoval na 40 MB).

Osobně bych si tipl, že to spolehlivě vymyslet bude pokus & omyl a pokud by někdo chtěl ladit velikost sliců a optimalizaci importu, může se na to napsat procesor a ten parametrizovat přímo na míru konkrétnímu use case.

**Comment by Halama** [comment]
Jo jasně. Já jsem právě začal tak že jsem hledal jestli na to nemáme processor, pak jsem si říkal že bysme ho mohli udělat. A pak mě napadlo proč s tím trápit usery když to můžeme dělat automaticky.

Je ale pravda že to udělat funkčně by asi nebyla sranda tak asi bude lepší processor pro ty use casy kde bude tohle problém.

**Comment by Halama** [comment]
Jo a založil jsem to kvůli tomhle https://connection.keboola.com/admin/projects/258/jobs/467243082?q=token.description%3Amartin.halamicek%40keboola.com 
46k slices, 1M řádek a import 2 hod.

**Comment by ondrejhlavacek** [comment]
Měli jsme merge procesor, kterej jsme skryli, protože se místo toho používaj slicy - `keboola.processor.merge`, možná se to s ním ještě může vyzkoušet. Tenhle setup je přesně ten edge case, kde se to mergnout stoprocentně vyplatí.

**Comment by Halama** [comment]
Tady to zavřu. Merge processor zafungoval skvěle https://connection.keboola.com/admin/projects/258/jobs/468169207
