### ISSUE TITLE
waitForJob parameter sanitization

### ISSUE THREAD

**Issue by odinuv** [keboola/storage-api-php-client#264]
PHP Notice:  Undefined index: id in Client.php on line 1905
PHP Notice:  Undefined index: status in Client.php on line 1906

to reproduce:
```
$client = new \Keboola\StorageApi\Client(['token' => 'xxxxxxxxxxxxxxxxxxxx', 'url' => 'https://connection.keboola.com/']);
$client->waitForJob('');
```

**Comment by ondrejhlavacek** [comment]
@odinuv stalo se to někde? nebo jen při nějakých pokusech/testech?

**Comment by odinuv** [comment]
to uz nevim, mel jsem to hrozne dlouho v todo listu

**Comment by ErikZigo** [comment]
Moved to Jira https://keboola.atlassian.net/browse/KBC-1790
