### ISSUE TITLE
Documentation is not up to date for async table export

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-php-client#281]
New filters and sort are missing https://keboola.docs.apiary.io/#reference/tables/unload-data/export-table-into-csv

@yustme sorry tohle jsem přehlídl ve review. Rovnou pak merguj.

**Comment by yustme** [comment]
@Halama není tahle metoda náhodou ta, kterou jsem odstranil minulý týden ?

**Comment by yustme** [comment]
v názvu issue je async export a v description je sync export. Tak teďka přesně nevím, co myslíš. 

Každopádně koukám, že where filters jsou nějaký špatně naformátovaný u async exportu, tak to opravím.

**Comment by Halama** [comment]
@yustme jo sorry máš pravdu. Jde o starý sync export a ten má jít pryč. V tom async je to ok https://keboola.docs.apiary.io/#reference/tables/unload-data/export-table-into-csv

**Comment by yustme** [comment]
Ok. Udělám tedy odstarnění https://github.com/keboola/storage-api-php-client/pull/282
