### ISSUE TITLE
validate getTable arguments

### ISSUE THREAD

**Issue by odinuv** [keboola/storage-api-php-client#306]
arguments of getTable call https://github.com/keboola/storage-api-php-client/blob/6322f0397b642c50fc21dcc716a06ef1d145a577/src/Keboola/StorageApi/Client.php#L811 are not validated, which means that empty string is accepted.

This causes the [list all tables](https://keboola.docs.apiary.io/#reference/tables/list-tables/list-all-tables) API call be used instead of the [table detail](https://keboola.docs.apiary.io/#reference/tables/manage-tables/table-detail) api call.

That means the response of the function changes from

```
array (
  'uri' => 'https://connection.keboola.com/v2/storage/tables/in.c-main.pokus',
```

to

```
array (
  0 =>
  array (
    'uri' => 'https://connection.keboola.com/v2/storage/tables/in.c-main.pokus',
```

which causes very strange errors, such as https://github.com/keboola/input-mapping/issues/34

**Comment by ErikZigo** [comment]
Moved to Jira https://keboola.atlassian.net/browse/KBC-1790
