### ISSUE TITLE
Not an instance of S3MultipartUploadException

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-php-client#323]
Error: https://keboola.slack.com/archives/C09U3R1J4/p1562654249040200

https://github.com/keboola/storage-api-php-client/blob/832c3c512657df95579a72156fb6b8ee8cbc2aa3/src/Keboola/StorageApi/S3Uploader/PromiseResultHandler.php#L21

```
UnexpectedValueException (0) in PromiseResultHandler.php line 21:
Not an instance of S3MultipartUploadException
Trace
in PromiseResultHandler.php line 21
at PromiseResultHandler::getRejected(array('/tmp/sapi-php-client/file-uploadxxx/xxx.csv.gz' => array('state' => 'rejected', 'reason' => object(RuntimeException)))) in S3Uploader.php line 145
```

**Comment by ErikZigo** [comment]
Moved to Jira https://keboola.atlassian.net/browse/KBC-1789
