### ISSUE TITLE
Documentation in apiary is missing admin section in response of token verification call

### ISSUE THREAD

**Issue by matejrokos** [keboola/storage-api-php-client#332]
Documentation: https://keboola.docs.apiary.io/#reference/tokens-and-permissions/token-verification/token-verification

Missing `admin` section in response body description.

**Comment by ujovlado** [comment]
https://github.com/keboola/storage-api-php-client/blob/5f831a060f1f380a84968c0ce283692d4aa1bae5/apiary.apib#L327

tam myslim este chyba aj "if any" ... ked to nie je admin token, ta info tam nie je.
