### ISSUE TITLE
Docs for FS register is out of date

### ISSUE THREAD

**Issue by yustme** [keboola/storage-api-php-client#338]
Při registrace FS chybí povinnost parametru "region". Dále je potřeba "container", který už potřeba není. Je podle toho taky potřeba předělat registrace FS v KBC

**Comment by ErikZigo** [comment]
Je to fixed, pro registrace filestorage má vlastní endpointy pro S3 i ABS s rozdílnýma parametrama https://keboolamanagementapi.docs.apiary.io/#reference/super-file-storage-management/create-new-azure-blob-storage
