### ISSUE TITLE
Keboola\StorageApi\Aws\Plugin\Backoff\BackoffPlugin does not catch internal error(?)

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/storage-api-php-client#35]
Syrup's S3 Uploader uses SAPI client's S3 client with backoff plugin (https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Aws/S3/Uploader.php#L45) but it did not catch internal error with message
"We encountered an internal error. Please try again.". It threw exception  `Aws\S3\Exception\InternalErrorException` and stack trace looks like this:
![https___keboola-logs_s3_amazonaws_com_debug](https://cloud.githubusercontent.com/assets/215660/8407570/48c522e4-1e68-11e5-8b0f-15ae0d92b4f9.png)

**Comment by Halama** [comment]
Backoff should be applied to this error according to https://github.com/keboola/storage-api-php-client/blob/5874cbd889bc7bc8b4f4a0ac72740e5ad9d6f803/src/Keboola/StorageApi/Aws/Plugin/Backoff/BackoffPlugin.php#L38 and http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Maybe it failed on all backoff attempts?
