### ISSUE TITLE
Components::updateConfiguration with empty configuration

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-php-client#58]
když chci přes klienta nastavit prázdnou konfiguraci

```
$components = new Components($client);
$options = new Configuration();
...
$options->setConfiguration(json_decode("{}");
$components->updateConfiguration($options);
```

tak tady https://github.com/keboola/storage-api-php-client/blob/e200dcf0b70686e43c81d28d42c29f316c6a5d54/src/Keboola/StorageApi/Components.php#L54 to neprojde a nenastaví se prázdná.

navíc metoda `setConfiguration` přetypuje `{}` na `[]` (což teď nedohlédnu, jestli je dobře nebo ne) - https://github.com/keboola/storage-api-php-client/blob/e200dcf0b70686e43c81d28d42c29f316c6a5d54/src/Keboola/StorageApi/Options/Components/Configuration.php#L113

narazil na to @kacurez, když chtěl v UI v docker appce uložit prázdnou konfiguraci, tak to tu starou nepřepsalo

**Comment by Halama** [comment]
fixed
