### ISSUE TITLE
Nezachycovaná vyjímka

### ISSUE THREAD

**Issue by tomasgura** [keboola/storage-api-php-client#94]
Našel jsem v souboru /src/Keboola/StorageApi/Client.php 
chybku, která se projeví např při volání bucketExists
vyjímka ClientException se nezachytí, protože v úvodu souboru chybí 
use GuzzleHttp\Exception\ClientException;

viz ukázka, je to i na víc místech. bucketExists nám házela vyjímky při integračních testech
public function bucketExists($bucketId)
    {
        try {
            $this->getBucket($bucketId);
            return true;
        } catch (ClientException $e) {
            if ($e->getCode() == 404) {
                return false;
            }
            throw $e;
        }
    }

chtěl jsem udělat pull request, ale nešlo mi to kvůli právům.
Tomáš Gůra
Economia a.s.

**Comment by ondrejhlavacek** [comment]
@tomasgura 

Zachycovaná výjimka `ClientException` je z namespace definovaného v třídě `Client` tj. `Keboola\StorageApi`, proto není třeba definovat tuto třídu v `use`. Výjimka se vyhazuje zde - https://github.com/keboola/storage-api-php-client/blob/e250f3476defacb1b20f49e5752fc3a625852611/src/Keboola/StorageApi/Client.php#L1619 a v testech https://github.com/keboola/storage-api-php-client/blob/e250f3476defacb1b20f49e5752fc3a625852611/tests/Backend/Common/BucketsTest.php#L170 je vidět, že pro neexistující bucket se vrací hodnota `false`

Pokud se vám to někde chová jinak, mohli byste nám poslat detaily, ať se na to můžeme podívat?

**Comment by tomasgura** [comment]
Díky za info. Mám v tom případě takový dotaz. Jak je to s verzí knihovny 4.5.
V integračních testech mi do dává právě tuhle vyjímku... mohla tam být chybka?

>> PHPUnit 5.5.7 by Sebastian Bergmann and contributors.
>>
>> W.........E...                                                    14 / 14 (100%)
>>
>> Time: 3.91 minutes, Memory: 23.25MB
>>
>> There was 1 error:
>>
>> 1) KeboolaAdapterIntegrationTest::testDeleteStorageBucketWithTables
>> GuzzleHttp\Exception\ClientException: Client error: `GET https://connection.keboola.com/storage/buckets/in.c-test_smazani` resu
lted in a `404 Not Found` response:
>> {"error":"Bucket in.c-test_smazani not found.","exceptionId":"keboola-connection-bb3fa725324de652bec7a32e98be8523","code
>>

**Comment by ondrejhlavacek** [comment]
Mohl byste nám ukázat ten test? Pokud nejde ve řekne, tak přes
support@keboola.com. Díky moc

**Comment by tomasgura** [comment]
No ono to vypadá že verze 4.16 knihovny chodí dobře, ale 4.5 dělá tuhle neplechu. Tak myslím, že se to vyřeší upgradem. Díky za Váš čas. Tomáš Gůra

**Comment by ondrejhlavacek** [comment]
Tak to je super zpráva. Kdybyste měli jakékoliv další potíže, ozvěte se. Díky!
